AllCops:
  TargetRubyVersion: 2.3
Layout/IndentArray:
  EnforcedStyle: consistent
Metrics/BlockLength:
  Exclude:
  - "*.gemspec"
  - "spec/**/*.rb"
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
