Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/IndentArray:
  EnforcedStyle: consistent
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
  - "*.gemspec"
  - "spec/**/*.rb"
